#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AREUOK.Resource", IsApplication=true)]

namespace AREUOK
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int RUOKHome = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int button1 = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int button2 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int button3 = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int button4 = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int button5 = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int button6 = 2131034121;
			
			// aapt resource value: 0x7f050003
			public const int linearLayout1 = 2131034115;
			
			// aapt resource value: 0x7f05000a
			public const int space1 = 2131034122;
			
			// aapt resource value: 0x7f050000
			public const int textView1 = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int textView2 = 2131034113;
			
			// aapt resource value: 0x7f05000b
			public const int textView3 = 2131034123;
			
			// aapt resource value: 0x7f050006
			public const int textView4 = 2131034118;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int About = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Home = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int QuestionnaireFifthScreen = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int QuestionnaireFirstScreen = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int QuestionnaireFourthScreen = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int QuestionnaireSecondScreen = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int QuestionnaireSummary = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int QuestionnaireThirdScreen = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040004
			public const int Impressum = 2130968580;
			
			// aapt resource value: 0x7f04000f
			public const int Q1of5 = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int Q2of5 = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int Q3of5 = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int Q4of5 = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int Q5of5 = 2130968595;
			
			// aapt resource value: 0x7f040015
			public const int Question1 = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int Question2 = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int Question3 = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int Question4 = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int Question5 = 2130968601;
			
			// aapt resource value: 0x7f040014
			public const int Score = 2130968596;
			
			// aapt resource value: 0x7f040003
			public const int about_button = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int back_button = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int change_lang_button = 2130968578;
			
			// aapt resource value: 0x7f04000c
			public const int continue_button = 2130968588;
			
			// aapt resource value: 0x7f040009
			public const int less_than_half_button = 2130968585;
			
			// aapt resource value: 0x7f04000d
			public const int less_than_thirteen = 2130968589;
			
			// aapt resource value: 0x7f040008
			public const int more_than_half_button = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int most_time_button = 2130968583;
			
			// aapt resource value: 0x7f04000b
			public const int never_button = 2130968587;
			
			// aapt resource value: 0x7f040001
			public const int questionnaire_button = 2130968577;
			
			// aapt resource value: 0x7f04000a
			public const int time_to_time_button = 2130968586;
			
			// aapt resource value: 0x7f04000e
			public const int total_score = 2130968590;
			
			// aapt resource value: 0x7f040006
			public const int whole_time_button = 2130968582;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
