#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AREUOK.Resource", IsApplication=true)]

namespace AREUOK
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int afraid = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Agitated = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int angry = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int beach_gauss = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int clouds_low = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int dawn_low = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int flower_pink_low = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int flower_red_low = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int forest_low = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int happy = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Icon = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int RUOKHome = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int RUOKHome_gauss = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int sad = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int sea_low = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000c
			public const int LinearLayoutMood = 2131034124;
			
			// aapt resource value: 0x7f050002
			public const int button1 = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int button2 = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int button3 = 2131034118;
			
			// aapt resource value: 0x7f05000b
			public const int button4 = 2131034123;
			
			// aapt resource value: 0x7f05002c
			public const int button5 = 2131034156;
			
			// aapt resource value: 0x7f05002d
			public const int button6 = 2131034157;
			
			// aapt resource value: 0x7f050025
			public const int buttonAway = 2131034149;
			
			// aapt resource value: 0x7f050027
			public const int buttonContinue = 2131034151;
			
			// aapt resource value: 0x7f050022
			public const int buttonEating = 2131034146;
			
			// aapt resource value: 0x7f050008
			public const int buttonExDB = 2131034120;
			
			// aapt resource value: 0x7f050026
			public const int buttonHome = 2131034150;
			
			// aapt resource value: 0x7f050021
			public const int buttonLeisure = 2131034145;
			
			// aapt resource value: 0x7f05001e
			public const int buttonMany = 2131034142;
			
			// aapt resource value: 0x7f050004
			public const int buttonMoodPeople = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int buttonMoodTime = 2131034115;
			
			// aapt resource value: 0x7f05001c
			public const int buttonNone = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int buttonOne = 2131034141;
			
			// aapt resource value: 0x7f050023
			public const int buttonWorking = 2131034147;
			
			// aapt resource value: 0x7f05002e
			public const int editText1 = 2131034158;
			
			// aapt resource value: 0x7f050011
			public const int imageViewHappyHowAreYou = 2131034129;
			
			// aapt resource value: 0x7f050018
			public const int imageViewLeftNegAffect = 2131034136;
			
			// aapt resource value: 0x7f050013
			public const int imageViewLeftPosAffect = 2131034131;
			
			// aapt resource value: 0x7f05001a
			public const int imageViewRightNegAffect = 2131034138;
			
			// aapt resource value: 0x7f050015
			public const int imageViewRightPosAffect = 2131034133;
			
			// aapt resource value: 0x7f05000f
			public const int imageViewSadHowAreYou = 2131034127;
			
			// aapt resource value: 0x7f05000a
			public const int linearLayout1 = 2131034122;
			
			// aapt resource value: 0x7f05001b
			public const int linearLayout2 = 2131034139;
			
			// aapt resource value: 0x7f050020
			public const int linearLayout3 = 2131034144;
			
			// aapt resource value: 0x7f050024
			public const int linearLayout4 = 2131034148;
			
			// aapt resource value: 0x7f05000e
			public const int linearLayout5 = 2131034126;
			
			// aapt resource value: 0x7f050017
			public const int linearLayout6 = 2131034135;
			
			// aapt resource value: 0x7f050009
			public const int listView1 = 2131034121;
			
			// aapt resource value: 0x7f05002a
			public const int plotViewModel = 2131034154;
			
			// aapt resource value: 0x7f050028
			public const int plotViewModelLeft = 2131034152;
			
			// aapt resource value: 0x7f050029
			public const int plotViewModelRight = 2131034153;
			
			// aapt resource value: 0x7f050030
			public const int radioButton1 = 2131034160;
			
			// aapt resource value: 0x7f050031
			public const int radioButton2 = 2131034161;
			
			// aapt resource value: 0x7f05002f
			public const int radioGroup1 = 2131034159;
			
			// aapt resource value: 0x7f05000d
			public const int scrollView1 = 2131034125;
			
			// aapt resource value: 0x7f050010
			public const int seekBar1 = 2131034128;
			
			// aapt resource value: 0x7f050019
			public const int seekBarNegAffect = 2131034137;
			
			// aapt resource value: 0x7f050014
			public const int seekBarPosAffect = 2131034132;
			
			// aapt resource value: 0x7f050005
			public const int space1 = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int textView1 = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int textView2 = 2131034113;
			
			// aapt resource value: 0x7f05001f
			public const int textView3 = 2131034143;
			
			// aapt resource value: 0x7f05002b
			public const int textView4 = 2131034155;
			
			// aapt resource value: 0x7f050016
			public const int textViewNegAffect = 2131034134;
			
			// aapt resource value: 0x7f050012
			public const int textViewPosAffect = 2131034130;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int About = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int History = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int History_List = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Home = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int MoodAssessment = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int PlotDoubleScreen = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int PlotScreen = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int QuestionnaireFifthScreen = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int QuestionnaireFirstScreen = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int QuestionnaireFourthScreen = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int QuestionnaireSecondScreen = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int QuestionnaireSummary = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int QuestionnaireThirdScreen = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Settings = 2130903053;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040041
			public const int Alone = 2130968641;
			
			// aapt resource value: 0x7f040030
			public const int Already5Times = 2130968624;
			
			// aapt resource value: 0x7f04002d
			public const int AnswerQuestions = 2130968621;
			
			// aapt resource value: 0x7f04002b
			public const int Away = 2130968619;
			
			// aapt resource value: 0x7f040021
			public const int DeleteAll = 2130968609;
			
			// aapt resource value: 0x7f04003b
			public const int Diagrams = 2130968635;
			
			// aapt resource value: 0x7f040045
			public const int Done = 2130968645;
			
			// aapt resource value: 0x7f040029
			public const int Eating = 2130968617;
			
			// aapt resource value: 0x7f04001d
			public const int English = 2130968605;
			
			// aapt resource value: 0x7f040044
			public const int ExampleDB = 2130968644;
			
			// aapt resource value: 0x7f040043
			public const int ExportDB = 2130968643;
			
			// aapt resource value: 0x7f040040
			public const int Frequency = 2130968640;
			
			// aapt resource value: 0x7f04001c
			public const int German = 2130968604;
			
			// aapt resource value: 0x7f04001f
			public const int Greeting = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int History = 2130968608;
			
			// aapt resource value: 0x7f04002c
			public const int Home = 2130968620;
			
			// aapt resource value: 0x7f040022
			public const int HowAreYou = 2130968610;
			
			// aapt resource value: 0x7f040003
			public const int Impressum = 2130968579;
			
			// aapt resource value: 0x7f04001b
			public const int Language = 2130968603;
			
			// aapt resource value: 0x7f040028
			public const int Leisure = 2130968616;
			
			// aapt resource value: 0x7f040026
			public const int Many = 2130968614;
			
			// aapt resource value: 0x7f04003e
			public const int Mood = 2130968638;
			
			// aapt resource value: 0x7f04003d
			public const int MoodPeople = 2130968637;
			
			// aapt resource value: 0x7f04003c
			public const int MoodTime = 2130968636;
			
			// aapt resource value: 0x7f040019
			public const int Name = 2130968601;
			
			// aapt resource value: 0x7f040036
			public const int NegAffect1 = 2130968630;
			
			// aapt resource value: 0x7f040037
			public const int NegAffect2 = 2130968631;
			
			// aapt resource value: 0x7f040038
			public const int NegAffect3 = 2130968632;
			
			// aapt resource value: 0x7f040039
			public const int NegAffect4 = 2130968633;
			
			// aapt resource value: 0x7f04003a
			public const int NegAffect5 = 2130968634;
			
			// aapt resource value: 0x7f040024
			public const int None = 2130968612;
			
			// aapt resource value: 0x7f040025
			public const int One = 2130968613;
			
			// aapt resource value: 0x7f040023
			public const int PeopleAroundYou = 2130968611;
			
			// aapt resource value: 0x7f040031
			public const int PosAffect1 = 2130968625;
			
			// aapt resource value: 0x7f040032
			public const int PosAffect2 = 2130968626;
			
			// aapt resource value: 0x7f040033
			public const int PosAffect3 = 2130968627;
			
			// aapt resource value: 0x7f040034
			public const int PosAffect4 = 2130968628;
			
			// aapt resource value: 0x7f040035
			public const int PosAffect5 = 2130968629;
			
			// aapt resource value: 0x7f04000e
			public const int Q1of5 = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int Q2of5 = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int Q3of5 = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int Q4of5 = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int Q5of5 = 2130968594;
			
			// aapt resource value: 0x7f040014
			public const int Question1 = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int Question2 = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int Question3 = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int Question4 = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int Question5 = 2130968600;
			
			// aapt resource value: 0x7f04002f
			public const int ReminderText = 2130968623;
			
			// aapt resource value: 0x7f04002e
			public const int ReminderTitle = 2130968622;
			
			// aapt resource value: 0x7f040013
			public const int Score = 2130968595;
			
			// aapt resource value: 0x7f04001e
			public const int Settings = 2130968606;
			
			// aapt resource value: 0x7f04001a
			public const int Standard_Name = 2130968602;
			
			// aapt resource value: 0x7f04003f
			public const int Time = 2130968639;
			
			// aapt resource value: 0x7f040027
			public const int WhatAreYouDoing = 2130968615;
			
			// aapt resource value: 0x7f040042
			public const int WithPeople = 2130968642;
			
			// aapt resource value: 0x7f04002a
			public const int Work = 2130968618;
			
			// aapt resource value: 0x7f040002
			public const int about_button = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int back_button = 2130968580;
			
			// aapt resource value: 0x7f04000b
			public const int continue_button = 2130968587;
			
			// aapt resource value: 0x7f040008
			public const int less_than_half_button = 2130968584;
			
			// aapt resource value: 0x7f04000c
			public const int less_than_thirteen = 2130968588;
			
			// aapt resource value: 0x7f040007
			public const int more_than_half_button = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int most_time_button = 2130968582;
			
			// aapt resource value: 0x7f04000a
			public const int never_button = 2130968586;
			
			// aapt resource value: 0x7f040001
			public const int questionnaire_button = 2130968577;
			
			// aapt resource value: 0x7f040009
			public const int time_to_time_button = 2130968585;
			
			// aapt resource value: 0x7f04000d
			public const int total_score = 2130968589;
			
			// aapt resource value: 0x7f040005
			public const int whole_time_button = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
